### ISSUE TITLE
add list of case studies to README

### ISSUE THREAD

**Issue by iantaylor-NOAA** [NOAA-FIMS/case-studies#16]
As the number increases, a list would be helpful. The github.io page includes links to each case study in the navigation bar, but this isn't as clear as a README list.

List could include a column stating the status as in-progress vs complete. 

Or maybe incomplete case studies should all be in branches (e.g. https://github.com/NOAA-FIMS/case-studies/tree/NWFSC-petrale).

Relates to #6.

**Comment by iantaylor-NOAA** [comment]
Expanding the README to include more info on the current goals of the case studies
Current goals for the case-studies discussed with @ChristineStawitz-NOAA, @Bai-Li-NOAA, @Andrea-Havron-NOAA, @k-doering-NOAA, and @nathanvaughan-NOAA during sea-side chat include:
* provide a way for the FIMS implementation team to learn more about the current ways of interacting with FIMS
* help identify ways that the input and output needs to be improved
* identifying common model needs across regions to inform prioritization of features

**Comment by k-doering-NOAA** [comment]
Thanks for capturing @iantaylor-NOAA, and for bringing up your thoughts on purpose of the case studies during the seaside chat!

**Comment by iantaylor-NOAA** [comment]
I just added a list (or table) of case studies to the README in 6f938ad.
I'll leave this issue open in case folks want to suggest additional refinements, such as 
* add column for point of contact?
* add column for name of assessment platform used in status-quo model?
* make table available on the quarto site homepage by adding to https://github.com/NOAA-FIMS/case-studies/blob/main/index.qmd (might require R script to modify index.qmd by github action if we want a single table to appear in both places)?

**Comment by kellijohnson-NOAA** [comment]
@iantaylor-NOAA and @Bai-Li-NOAA I am happy with the current table and this issue has been stale since April 26th without any further suggestions so I think it should be closed.
