### ISSUE TITLE
SWFSC Sardine example 404 error

### ISSUE THREAD

**Issue by nathanvaughan-NOAA** [NOAA-FIMS/case-studies#2]
the SWFSC Sardine example loads locally by throws a 404 page not found error online.

**Comment by nathanvaughan-NOAA** [comment]
Part of the error appears to be due to the link trying to load to 

https://noaa-fims.github.io/case-studies/content/SwFSC-sardine.qmd

which does not match the file name due to the lower case "w" instead of the correct upper case. 

It seems that this is correctly specified in the _quarto.yml file but is still not working and I'm not sure where else this needs to be specified.

**Comment by Bai-Li-NOAA** [comment]
Done through pull request #4
