### ISSUE TITLE
Specifying obs error for fleet

### ISSUE THREAD

**Issue by peterkuriyama-NOAA** [NOAA-FIMS/case-studies#21]
I am getting this error: "Error in as.environment(-2.9) : invalid 'pos' argument" when specifying the observation error for a fleet. I get this error when I try to run existing case studies locally. It does not seem to be an issue when running on codespaces. 

Below is some example code:

fish_fleet <- methods::new(Fleet)
fish_fleet$nages <- 9
fish_fleet$nyears <- 19
fish_fleet$log_Fmort <- log(rep(0.00001, 19))
fish_fleet$estimate_F <- TRUE
fish_fleet$random_F <- FALSE
fish_fleet$log_q <- 0 #Not sure if this will be right
fish_fleet$estimate_q <- FALSE
fish_fleet$random_q <- FALSE

Here are some values that resulted in an error
# Error in as.environment(-2.9) : invalid 'pos' argument
fish_fleet$log_obs_error <- log(sqrt(log(0.05 ^ 2 + 1))) #invalid 'pos' argument
fish_fleet$log_obs_error <- -2.9 #Error in as.environment(-2.9) : invalid 'pos' argument
fish_fleet$log_obs_error <- .5 #Doesn't work

These values seem to work
fish_fleet$log_obs_error <- 1 
fish_fleet$log_obs_error <- -1 
fish_fleet$log_obs_error <- -1.1

**Comment by ChristineStawitz-NOAA** [comment]
@peterkuriyama-NOAA can you try inputting `log_obs_error` as a vector and see if that works? @Andrea-Havron-NOAA and group are working on a fix as part of the NLL refactor to change scalar values to vectors so the error message is more informative.

**Comment by ChristineStawitz-NOAA** [comment]
@Bai-Li-NOAA will test if there are some values that are resulting in errors in the model

**Comment by Andrea-Havron-NOAA** [comment]
It looks like this error is coming from the assign function in R. Look at `?assign()` for more details. The value is going into the `pos` argument of `asign()` instead of the `value` argument. Try adding a space after `<-` or wrapping values with `()` to see if that helps. This is one of those mysterious R errors!

**Comment by Bai-Li-NOAA** [comment]
Close this issue, as @peterkuriyama-NOAA hasn't had the errors since using the most recent version of FIMS. A new issue  ([#622](https://github.com/NOAA-FIMS/FIMS/issues/622)) has been created in the FIMS repo to check the length of input vectors.
