### ISSUE TITLE
re-run github action manually or automatically when tinytex error occurs

### ISSUE THREAD

**Issue by iantaylor-NOAA** [NOAA-FIMS/case-studies#24]
Occasionally our Render on pull request fails with an error 
```
ERROR: Unable to determine latest release for rstudio/tinytex-releases
403 - Forbidden
```
I posted this quarto-dev issue https://github.com/quarto-dev/quarto-actions/issues/105 and was told "it's most likely a transient failure of the GitHub API (or the github action runners themselves)".

Therefore, I think the best two options are either to
1. increase awareness (e.g. via this issue) of the problem as something outside of FIMS (or Quarto), so that we know to manually re-run the action get it working again, and/or
2. revise our github action as suggested by @Bai-Li-NOAA during the today's seaside chat to detect this failure and re-run the action automatically.

**Comment by iantaylor-NOAA** [comment]
Update: recent failed action required 4 tries to get past this error. Still not clear if it's worth doing anything other than re-running actions manually, but wanted to make sure we have a record of what it can take to get working.
![image](https://github.com/NOAA-FIMS/case-studies/assets/4992918/425f368c-ee38-41d6-941e-9e20992439e2)

**Comment by k-doering-NOAA** [comment]
Ugh, this seems really frustrating! I don't understand why we would be seeing this issue, but the quarto actions folks do not.

I wonder if we could pin the tinytex version and if that would change the need to rerun? I can't think of anything else to try.

**Comment by kellijohnson-NOAA** [comment]
I have a few ideas but I am not sure if either of them will work
1. Try to install tinytex a different way so it is already available before the quarto install
2. Use a different operating system than Mac

**Comment by k-doering-NOAA** [comment]
Ah, this is super helpful!

I think we should add this to the setup step:

```
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

based on the [docs here](https://github.com/quarto-dev/quarto-actions/tree/main/setup#inputs-available). It seems like the setup step is looking for an environmental variable called `GH_TOKEN`, which we have not set.

If the problem persists, I think we can swap secrets.GITHUB_TOKEN for a personal access token.
