### ISSUE TITLE
Figure out why yellowtail NEFSC won't run in quarto book

### ISSUE THREAD

**Issue by ChristineStawitz-NOAA** [NOAA-FIMS/case-studies#3]
Tagging Chris since we probably need to work together on it - although I can use help figuring out why the Yellowtail example that runs locally doesn't work in this quarto book

**Comment by Bai-Li-NOAA** [comment]
I got the following error while running the quarto book locally:

```r
Error in eval(expr, envir, enclos) :
  Not compatible with requested type: [type=list; target=double]
```
GitHub Action log indicates that the errors were associated with the log_obs_error settings. The updated code below, using the latest FIMS interface, resolved the issue on my local machine:
```r
fishing_fleet$log_obs_error <- rep(log(sqrt(log(as.numeric(mean(rdat$control.parms$catch.tot.cv[,1], na.rm=TRUE)^2) + 1))), nyears)
fishing_fleet$estimate_obs_error <- FALSE

survey_fleet$log_obs_error <- rep(log(sqrt(log(as.numeric(mean(rdat$index.cv[[i]], na.rm=TRUE)^2 + 1)))), nyears)
survey_fleet$estimate_obs_error <- FALSE

**Comment by Bai-Li-NOAA** [comment]
Done through pull request #4
