### ISSUE TITLE
Pull request failing and failure to render quarto files locally

### ISSUE THREAD

**Issue by peterkuriyama-NOAA** [NOAA-FIMS/case-studies#36]
I've rebased the swfsc-sardine branch but am still not able to get the quarto files to render. The code is crashing when trying to build the FIMS model for the nefsc-yellowtail example with the following specs:
> R_version
[1] "R version 4.3.2 
> TMB_version
[1] "1.9.11"
> FIMS_commit
[1] "9f13e8d"

The nefsc-yellowtail example works fine if I manually load the packages and run the code outside of the quarto workstream

**Comment by Bai-Li-NOAA** [comment]
@peterkuriyama-NOAA. The issue has been resolved with PR #37. Please check out the sardine case study online and feel free to modify the qmd file as needed.
