### ISSUE TITLE
github action failing, perhaps related to redundant files

### ISSUE THREAD

**Issue by iantaylor-NOAA** [NOAA-FIMS/case-studies#39]
This is a low priority issue that should wait until after the holiday to be dealt with.

@KyleShertzer-NOAA got the scamp model working (passing "Render on pull request") but after merging the "[Render and Plublish](https://github.com/NOAA-FIMS/case-studies/actions/runs/9782490568)" github action failed

The failure is in rendering `pc.qmd`, which was added in commit https://github.com/NOAA-FIMS/case-studies/commit/5d2e658eaac0323471f6da73b66f7a028f2af82c, that file seems to be a slightly modified version of https://github.com/NOAA-FIMS/case-studies/blob/main/content/AFSC-GOA-pollock.qmd.
@peterkuriyama-NOAA, was the addition of `pc.qmd` intentional?

@Bai-Li-NOAA may also have insights after editing that file.

**Comment by Bai-Li-NOAA** [comment]
@KyleShertzer-NOAA, the pull request #40 should resolve the rendering issue. Please review the SEFSC case study [here](https://noaa-fims.github.io/case-studies/content/SEFSC-scamp.html) and let me know if you have any questions.
