### ISSUE TITLE
[Developer Issue]: Remove TMBHelper from case studies

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [NOAA-FIMS/case-studies#43]
### Description

@Cole-Monnahan-NOAA you mentioned (https://github.com/NOAA-FIMS/FIMS/issues/551#issuecomment-2237009982 ) that the instance of `TMBHelper` in your case study can be removed but I am wondering if you want to do that or if you want help? If you want, I can start a branch with a PR that removed the other calls to TMBHelper from non-alaska case studies as a start. You can also reply to this issue with a fix and I (or someone else) can implement it. I just don't want the task to be lost in GitHub. Here is the line that needs changed
https://github.com/NOAA-FIMS/case-studies/blob/c0f7e1c5e5cabc21dcf17e13c6d66c24a42ccfbb/content/AFSC-GOA-pollock.qmd#L102

**Comment by Cole-Monnahan-NOAA** [comment]
Removed with [this commit](https://github.com/NOAA-FIMS/case-studies/commit/434e7712e9f008b34052c4ff84c1a585e3783130).
