### ISSUE TITLE
Automate the installation of required packages

### ISSUE THREAD

**Issue by Bai-Li-NOAA** [NOAA-FIMS/case-studies#5]
It would be nice to automate the installation of required packages when developers render the book locally. I have added [a few lines of code](https://github.com/NOAA-FIMS/case-studies/blob/125ae1f276bccebb5a384f87deba333f4adb2d48/content/NEFSC-yellowtail.qmd#L12C1-L25C14) within the NEFSC yellowtail example to automatically install missing packages.

However, duplicating this code for each case study may be redundant. Maybe we can explore an alternative solution to include a DESCRIPTION file and utilize the {attachment} package to install missing dependencies. See examples [here](https://github.com/ThinkR-open/attachment#allow-the-ci-to-install-all-dependencies-required-for-your-bookdown-pagedown-quarto-).

**Comment by ChristineStawitz-NOAA** [comment]
thanks @Bai-Li-NOAA ! I had the same thought about not duplicating the code - I tried to put it in the index file but I am not sure of the order of compilation of the bookdown. I was thinking of turning it into a package, but if just adding a DESCRIPTION file lets us manage without the package step that seems even better!

**Comment by Bai-Li-NOAA** [comment]
Great, I will explore the DESCRIPTION approach and provide updates on my progress here.
