### ISSUE TITLE
AFSC pollock case study does not render on remote repo

### ISSUE THREAD

**Issue by Bai-Li-NOAA** [NOAA-FIMS/case-studies#8]
The AFSC pollock case study renders successfully locally but it does not render on remote repo. 

The [warning]((https://github.com/NOAA-FIMS/case-studies/actions/runs/7834911963/job/21380492632#step:8:89)) from the FIMS installation process:
```
Warning in checkMatrixPackageVersion(getOption("TMB.check.Matrix", TRUE)) :
  Package version inconsistency detected.
TMB was built with Matrix version 1.6.4
Current Matrix version is 1.6.1.1
Please re-install 'TMB' from source using install.packages('TMB', type = 'source') or ask CRAN for a binary version of 'TMB' matching CRAN's 'Matrix' package
```

The [error](https://github.com/NOAA-FIMS/case-studies/actions/runs/7834911963/job/21380492632#step:8:101) after running [run-FIMS] section of code:
```
*** caught segfault ***
address 0x0, cause 'memory not mapped'
```

The pollock case study needs to use the FIMS isNA branch, but I am not sure if GHA is installing the correct version of FIMS for this case study. When I tried to use the latest version of FIMS locally for this case study, I encountered the following error:
```r
Quitting from lines 94-190 [run-FIMS] (AFSC-GOA-pollock.qmd)
Error in `nlminb()`:
! NA/NaN gradient evaluation
Backtrace:
 1. TMBhelper::fit_tmb(obj, getsd = FALSE, newtonsteps = 0, control = list(trace = 100))
 2. stats::nlminb(...)                                                                                                      
Execution halted
```

Potential solutions to try:
- [x]  Force installing FIMS isNA branch in the case study
- [ ]  Re-install 'TMB' from source using install.packages('TMB', type = 'source') in the case study

**Comment by Bai-Li-NOAA** [comment]
The case study is using FIMS isNA branch. This has been tested through commit 436f60546066972b000646ec450dba9b6086cbd8.

**Comment by Cole-Monnahan-NOAA** [comment]
Just an FYI it will fail on the main branch b/c I'm inputting negative observations for both the indices and age compositions (-999) so those will be logged and thus NaN so the likelihood calculations break downstream. That's expected.
